### ISSUE TITLE
patient-ssapp browse trials "LEARN MORE" button vertical centering

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/ctr-workspace#20]
The clickeable prototype specifies:
![image](https://user-images.githubusercontent.com/77448470/126311956-bce6683e-3b5f-406e-9740-2d99e337cc0d.png)

The current v0.4.14 patient-ssapp displays:
![image](https://user-images.githubusercontent.com/77448470/126312033-bb89f733-1566-4dbe-96c3-9e7a96c91ba4.png)

This issue is specifically about vertical centering of the "LEARN MORE" button.

(The search form and  "REMOVE SELECTED" mechanism is missing, but these are not the scope of this issue).

**Comment by joaoluis-pdm** [comment]
Hi! @lehialessandro 
Thanks for the proposed fix.
The solution presented in b26c34377d374b6fe08d547eac88401081a3f009 vertically aligns all the row elements, including the text. In the clickable prototypes, the texts are aligned to the top.
Can we achieve that easily ? Or we just leave it as is, and say it is like that ?

**Comment by lehialessandro** [comment]
Hi! @joaoluis-pdm 
I'll add both texts and checkbox aligned to the top.

**Comment by joaoluis-pdm** [comment]
Thanks @lehialessandro 
Closing the issue.
