### ISSUE TITLE
patient-ssapp (and ctr-backoffice-frontend) should display a map for each ClinicalSite address

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/ctr-workspace#21]
The clickeable prototype specifies:
![image](https://user-images.githubusercontent.com/77448470/126313340-8d2f0c67-75f0-4461-9ab8-32334b8d14e4.png)

The current patient-ssapp v0.4.14 displays:
![image](https://user-images.githubusercontent.com/77448470/126313424-04d39e46-0196-4f4c-ae25-16f9dbae1a0b.png)

For example https://github.com/PharmaLedger-IMI/acdc-workspace/tree/master/backoffice-frontend/src/app/event-detail
uses LeafletJS to display the map.

(To display the traveling distance, we must also solve the knowing of the current user position. At this time it is not clear if that is in-scope or out-of-scope of this issue).

This is also related to issue #14 (support multiple Clinical Sites), depends on what is fixed first, the scope is to display just a single ClinicalSite or multiple ClinicalSites.
PDM proposal is to finish the MVP with support for a single ClinicalSite.

**Comment by joaoluis-pdm** [comment]
It is still needed to do the same on 
ctr-patient/patient-ssapp/code/scripts/controllers/MatchRequestNew60InfoController.js
and 
ctr-patient/patient-ssapp/code/templates/matchrequestnew60info.html

(... then I probably have to add the display and sorting by clinicaltrial.travelDistance).

**Comment by pccosta-pdm** [comment]
added to display a map on (clinical trials match request):
ctr-patient/patient-ssapp/code/scripts/controllers/MatchRequestNew60InfoController.js
and
ctr-patient/patient-ssapp/code/templates/matchrequestnew60info.html

**Comment by joaoluis-pdm** [comment]
Seems done! Thank you @pccosta-pdm .
