### ISSUE TITLE
patient-ssapp v0.6.0 "BROWSE TRIALS" is limited to 100 trials on the server side

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/ctr-workspace#28]
Implement a "paginator" on the patient-ssapp client side to browse pages of trials sorted by a particular condition (as it is +/- done in the physician backoffice).

**Comment by pccosta-pdm** [comment]
Ready for review

**Comment by joaoluis-pdm** [comment]
Considering it closed. Thank you @pccosta-pdm
