### ISSUE TITLE
patient-ssapp should allow "BROWSE TRIALS" to filter by condition, location+distance, and recruiting stage

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/ctr-workspace#42]
Desired screen for "BROWSE TRIALS"
![image](https://user-images.githubusercontent.com/77448470/131828124-ac1b9aa1-7c56-48fa-b6e5-19de971ce413.png)

Current v0.7.3:
![image](https://user-images.githubusercontent.com/77448470/131828356-8cd29082-438a-4789-87c5-b56bc9dd21f3.png)

**Comment by pccosta-pdm** [comment]
@joaoluis-pdm I created a component to perform the filtering. Currently the filter options are "hardcoded". These options should come from a get request, so instead of using the "lforms routes/requests" these need to be implemented

**Comment by joaoluis-pdm** [comment]
Seems to work. Please merge to master so that we can continue to work on the other pull-downs (Condition, Location, Travel Distance, etc...)

**Comment by joaoluis-pdm** [comment]
@pccosta-pdm Seems to work! Good!
Please merge to master so that we can continue to work on the other pull-downs (Condition, Location, Travel Distance, etc...)

**Comment by joaoluis-pdm** [comment]
Next steps (pick your favorite :-)
- fill medical condition from web-service /borest/lforms/medicalconditions but first we have to decide if to handle issue #44 , or to create a middleware proxy for it, or if hide this #44 problem inside a MatchManager.getMedicalConditions() method (or other) ?
- let the location (optional) be filled from location API (as in 2c9d80bbc37a27075e441c974c40be46e2894f27 ) and sort results by travel distance (unless Travel Distance is any).
- limit the status to "Recruiting", "Published", "Closed". Will possibly be changed in a near future.

**Comment by joaoluis-pdm** [comment]
Some conditions have long names...
![image](https://user-images.githubusercontent.com/77448470/132894707-c7ca443b-645a-4e56-acbe-54e3d882589b.png)

**Comment by pccosta-pdm** [comment]
@joaoluis-pdm added some responsive features to filter options and travel distance when location is provided.

some other changes: the filter is now controlled by the page controller, instead of inside the component.

**Comment by joaoluis-pdm** [comment]
Seems good enough. Let's close the issue for now, and wait for user's feedback.

**Comment by joaoluis-pdm** [comment]
Technical Meeting 2021-09-14:

At the "Browse Trials" filter, the location pull-down
![image](https://user-images.githubusercontent.com/77448470/133301604-61e4e895-126e-4057-b3f4-4bba47d89ab0.png)
should show the same options as in the "Find a trial" / Where are you located question:
![image](https://user-images.githubusercontent.com/77448470/133301691-f7b91383-324a-4d97-b026-72c3fe955b12.png)

**Comment by joaoluis-pdm** [comment]
The list of locations comes from 
https://ctr2-dev.pharmaledger.pdmfc.com/borest/lforms/locations

PS: For now I accept something similar to https://github.com/PharmaLedger-IMI/ctr-workspace/commit/74158e4b117f50614c78e93e8cfb04e95217e18d

**Comment by pccosta-pdm** [comment]
added location options provided by the web service.

**Comment by joaoluis-pdm** [comment]
For now lets assume that this issue is ok (good enough).

Notes;
- There has already been some overlapping changes in #14 
- It would be nice to optimize the patient-ssapp to ask permission to get the patient location only once - when the patient clicks "My Locarion" (or at least only once every hour, instead of every time that the patient enters the screen to browse trials).

But all of these notes are a bit of of scope. So I consider this issue reviewed and closed.

Thank you @pccosta-pdm !
