### ISSUE TITLE
Fix 'Phisical' typo 

### ISSUE THREAD

**Issue by rdogum** [PharmaLedger-IMI/ctr-workspace#46]
In the trial match result view, 'Phisical Commitment' should be 'Physical Commitment'

![image](https://user-images.githubusercontent.com/16582818/132724241-e5bd087c-e393-4333-8ca1-eeca761b8891.png)

Note: this should be a minor quick fix. Testing the github issues. Thanks!

**Comment by joaoluis-pdm** [comment]
Hi @rdogum !
This is already fixed on v0.8.x in DEV https://ctr-dev.pharmaledger.pdmfc.com/
(Commit evidence  446ef221cdc3f37242c127e5676bec18e41b0fd5 )

So I am closing this issue, and moving it to the Done board.
Please re-open if you don't think this is the proper fix.
