### ISSUE TITLE
Patient contact clinical site

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/ctr-workspace#50]
(This is an extension of issue #5 )

Implement the feature for patients to contact a clinical site when viewing a match result (with a positive match) or answering a pre-screener for a single trial that matched.

![image](https://user-images.githubusercontent.com/77448470/134357187-e7a5a898-4dce-447d-9e8c-01c9b44ce9f5.png)

Email from: 14th September 2021 17:54

> Meanwhile, I re-send below one blocking question to develop F-6-4 (Clinical Sites need to access patient enrollment status).
(Short version: If all the contact between the patient and the clinical site goes through the patient-ssapp, then we have to develop those 2-way "messaging features" from scratch. If the patient supplies an email or phone for clinical site contact, then the patient is no longer anonymous - from that point on. ... But I guess that this last option is unavoidable).

Meeting 2021-09-21:

> PDM will implement an extra dialog on contacting the clinical site to ask the patient to confirm the name and email for contact purposes.

**Comment by joaoluis-pdm** [comment]
The "My Patients" backoffice view (from the Clinical Site app) will not be implemented:

![image](https://user-images.githubusercontent.com/77448470/134336417-b1d18fd0-4fff-403c-9152-5311a9e9128f.png)

because that would imply that the identity of the patient is established across multiple-trials, and contradicts the "de-identified patient" requirement.

So far each patient application has only a name and email (and possibly phone), and there is no patient identity concept on the database.

**Comment by joaoluis-pdm** [comment]
**ctr-patient/patient-ssapp changes:**

Controllers ClinicalTrialAns60InfoController, MatchInfo20Controller, MatchRequestNew60InfoController: When there is a match enable (display) the "CONTACT CLINICAL SITE" button, and handle it.

The button handled should display a modal asking for:
```
Name: ... filled with the default participant name
Email: ... filled with the default participant email
I authorise the clinical site to use this data (along with my pre-screener answers) for trial contact purposes.
CONTACT
```
When the "CONTACT" button is pressed, it must call the middleware /ctr-match-service/trialFind using a new method in ctr-patient/ctr-dsu-wizard/services/MatchRequestService.js "apply(data, callback(err))". See REST parameters for data contents.

(It may not be a modal, but at this time seems that a model might be easier to write).


**ctr-patient/ctr-dsu-wizard/middleware changes:**

Associate a new localhost endpoint /ctr-match-service/apply to call REST /borest/ctrms/apply

**ctr-backoffice-backend changes:**

POST /borest/ctrms/apply - create a new Application record. The body must contain:
```
{
    name: "string",
    email: "string",
    matchRequest: "const keySSI string",
    clinicalSite: "UUID string",
    clinicalTrial: "UUID string"
}
```

GET /borest/ctrial/application?clinicalTrial=UUID - return a paged list of applications for this trial. Use the same paged parameters as in GET /borest/ctrial/clinicaltrial

**Comment by joaoluis-pdm** [comment]
@pccosta-pdm the name is "undefined undefined"
![image](https://user-images.githubusercontent.com/77448470/134771398-2951938d-c468-46c4-9f9e-a2c6c2aa2dcc.png)
(also the name and email are supposed to be editable, but for the moment, we may consider leaving this from the target for next tuesday morning).

**Comment by joaoluis-pdm** [comment]
@pccosta-pdm 
the implementation at MatchInfo20Controller.js seems broken.
![image](https://user-images.githubusercontent.com/77448470/134784194-281c23c5-2f19-4c1d-9f16-346d75739f81.png)

**Comment by joaoluis-pdm** [comment]
@pccosta-pdm another error candidate (might not be an error)
![image](https://user-images.githubusercontent.com/77448470/134883236-faa80a87-93be-467a-af2f-abe040ae2374.png)
```
contact-clinical-site-button.patientIdentity newValue=  error= SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ContactClinicalSiteButton.watchPatientIdentity (contact-clinical-site-button.entry.js:31)
    at index-7c719aff.js:1839
    at Array.map (<anonymous>)
    ...
```

**Comment by pccosta-pdm** [comment]
@joaoluis-pdm, issues fixed.

on

> contact-clinical-site-button.patientIdentity newValue=  error= SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ContactClinicalSiteButton.watchPatientIdentity (contact-clinical-site-button.entry.js:31)
    at index-7c719aff.js:1839
at Array.map (<anonymous>)
...

it's not a "error" (it's because on the application initialization the initial value is "undefined"), however I put a condition to show the message when the property is set intentionally.

**Comment by joaoluis-pdm** [comment]
Seems all fixed!

**Comment by joaoluis-pdm** [comment]
@pccosta-pdm 
The "CONTACT CLINICAL SITE" seems to allow contact even if there is no match. That seems a defect.
![image](https://user-images.githubusercontent.com/77448470/135065163-ebb98349-274a-478e-91ec-536837969dc8.png)


... as the spec says
>  When there is a match enable (display) the "CONTACT CLINICAL SITE" button, and handle it.

**Comment by joaoluis-pdm** [comment]
@pccosta-pdm the check for double-contact  should be done using an internal database that also appears on the dashboard:
![image](https://user-images.githubusercontent.com/77448470/135105406-7b8af3e9-9390-43f4-be11-7d0dc89c4513.png)

**Comment by joaoluis-pdm** [comment]
Meeting 2021-09-28:

"My Application" -> "My Referrals"

**Comment by joaoluis-pdm** [comment]
@pccosta-pdm commit d90a0c9 seems to work. Review complete. Thanx!

**Comment by joaoluis-pdm** [comment]
Multi-site changes handled within #14.
Available on v0.10.3

**Comment by joaoluis-pdm** [comment]
Meeting 2021-09-28 CTR Weekly: Ask for phone number.

**Comment by joaoluis-pdm** [comment]
Patient phone number must be filled manually, as it is not part of the patient wallet information.

**Comment by joaoluis-pdm** [comment]
From the weekly business meetings, there is a request to add a "status" attribute

Adding a "status" attribute will raise the need to define a workflow (what are the possible statuses, and what can be done at each status).

To avoid that, the tech team simply counter-proposes the export of this data to CSV, and let the application processing workflow be external to the software.

**Comment by joaoluis-pdm** [comment]
Using https://www.npmjs.com/package/mat-table-exporter

**Comment by joaoluis-pdm** [comment]
Meeting 2022-01-04

On the Clinical Site App, rename wording of "Application" -> to "Referrals".

**Comment by joaoluis-pdm** [comment]
Meeting 2022-01-04

The Export-to-CSV needs to export the whole table, not only the visible results,  so 
b284c85 
should do that.
